apiVersion: 1

datasources:
  - name: PostgreSQL Demo
    uid: postgres-demo
    type: postgres
    access: proxy
    url: postgres:5432
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      database: grafana_demo
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
